version: "3.8"

services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    links:
      - auth-service
    depends_on:
      - auth-service
    networks:
      - microservice-network

  auth-service:
    build:
      context: ./auth-service/
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - MONGO_URI=mongodb://db:27017/authDB
      - PORT=3000
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - microservice-network
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  data:
    driver: local
